# Generated by Django 4.2.3 on 2023-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clie_nombre', models.CharField(max_length=45, verbose_name='Nombre Cliente')),
                ('clie_apellido', models.CharField(max_length=45, verbose_name='Apellido Cliente')),
                ('clie_telefono', models.CharField(max_length=15, verbose_name='Teléfono Cliente')),
                ('clie_direccion', models.CharField(max_length=45, verbose_name='Dirección Cliente')),
                ('clie_tipo_documento', models.IntegerField(choices=[(0, 'CC'), (1, 'CE'), (2, 'PEP'), (3, 'PA'), (4, 'NIT'), (5, 'OTRO')], default=0, verbose_name='Tipo documento')),
                ('clie_num_documento', models.CharField(max_length=25, verbose_name='Numero de documento')),
                ('clie_correo_electronico', models.CharField(max_length=45, verbose_name='Correo cliente')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vent_fecha', models.DateField(verbose_name='Fecha de venta')),
                ('vent_precio_subtotal', models.IntegerField(verbose_name='Precio subtotal')),
                ('vent_iva', models.IntegerField(verbose_name='IVA')),
                ('vent_precio_total', models.IntegerField(verbose_name='Precio total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_vent_precio_unitario', models.IntegerField(verbose_name='Precio unitario de producto')),
                ('det_vent_cantidad', models.IntegerField(verbose_name='Cantidad producto')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('cliente_clie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NumCliente', to='ventas.cliente', verbose_name='Número de cliente')),
                ('vent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NumVenta', to='ventas.venta', verbose_name='Número de venta')),
            ],
        ),
    ]
