# Generated by Django 4.2.3 on 2023-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nombre', models.CharField(max_length=45, verbose_name='Nombre usuario')),
                ('usu_apellido', models.CharField(max_length=45, verbose_name='Apellido usuario')),
                ('usu_num_doc', models.CharField(max_length=15, verbose_name='Número de documento')),
                ('usu_telefono', models.CharField(max_length=15, verbose_name='Número de teléfono')),
                ('usu_direccion', models.CharField(max_length=15, verbose_name='Dirección del usuario')),
                ('usu_email', models.CharField(max_length=15, verbose_name='Email del usuario')),
                ('usu_clave', models.CharField(max_length=15, verbose_name='clave del usuario')),
                ('usu_tipo_documento', models.IntegerField(choices=[(0, 'CC'), (1, 'CE'), (2, 'PEP'), (3, 'PA'), (4, 'NIT'), (5, 'OTRO')], default=0, verbose_name='Tipo documento')),
                ('usu_num_documento', models.CharField(max_length=25, verbose_name='Numero de documento')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_nombre', models.CharField(max_length=45, verbose_name='Nombre del servicio')),
                ('serv_codigo', models.CharField(max_length=45, verbose_name='Código del servicio')),
                ('serv_descripcion', models.CharField(max_length=45, verbose_name='Descripción del servicio')),
                ('serv_categoria', models.CharField(max_length=45, verbose_name='Categoría del servicio')),
                ('serv_pago_total', models.IntegerField(verbose_name='Pago total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario1', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nombre', models.CharField(max_length=45, verbose_name='Nombre del producto')),
                ('prod_codigo', models.CharField(max_length=45, verbose_name='Código del producto')),
                ('prod_descripcion', models.CharField(max_length=45, verbose_name='Descripción del producto')),
                ('prod_pre_compra', models.IntegerField(verbose_name='Precio de compra')),
                ('prod_pre_venta', models.IntegerField(verbose_name='Precio de venta')),
                ('Stock_min', models.IntegerField(verbose_name='Mínimo inventario')),
                ('Stock', models.IntegerField(verbose_name='Inventario')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario2', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insum_nombre', models.CharField(max_length=45, verbose_name='Nombre del insumo')),
                ('insum_categoria', models.CharField(max_length=45, verbose_name='Categoría del insumo')),
                ('insum_codigo', models.CharField(max_length=45, verbose_name='Código del insumo')),
                ('insum_cantidad', models.IntegerField(verbose_name='Cantidad de insumo')),
                ('insum_pre_compra', models.IntegerField(verbose_name='Precio de compra')),
                ('insum_total', models.IntegerField(verbose_name='Precio de venta')),
                ('Stock_min', models.IntegerField(verbose_name='Mínimo inventario')),
                ('Stock', models.IntegerField(verbose_name='Inventario')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuario3', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
