# Generated by Django 4.2.3 on 2023-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_fecha', models.DateField(verbose_name='Fecha de compra')),
                ('comp_precio_total', models.IntegerField(verbose_name='Compra, costo total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_nombre', models.CharField(max_length=45, verbose_name='Nombre proveedor')),
                ('prov_apellido', models.CharField(max_length=45, verbose_name='Apellido proveedor')),
                ('prov_nit', models.CharField(max_length=45, verbose_name='nit proveedor')),
                ('prov_telefono', models.CharField(max_length=15, verbose_name='Teléfono proveedor')),
                ('prov_direccion', models.CharField(max_length=45, verbose_name='Dirección proveedor')),
                ('prov_metodo_pago', models.IntegerField(choices=[(0, 'Efectivo'), (1, 'Tarjeta de crédito'), (2, 'Cheque'), (3, 'Transferencia bancaria')], default=0, verbose_name='Metodo de pago')),
                ('prov_tipo_documento', models.IntegerField(choices=[(0, 'CC'), (1, 'CE'), (2, 'PEP'), (3, 'PA'), (4, 'NIT'), (5, 'OTRO')], default=0, verbose_name='Tipo documento')),
                ('prov_num_documento', models.CharField(max_length=25, verbose_name='Número de documento')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_comp_precio_unitario', models.IntegerField(verbose_name='Precio unitario del insumo')),
                ('det_comp_cantidad', models.IntegerField(verbose_name='Cantidad producto')),
                ('det_comp_precio_total', models.IntegerField(verbose_name='Compra, costo total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Numcompra', to='compras.compra', verbose_name='Número de compra')),
                ('usu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ID_usuario', to='usuarios.usuario', verbose_name='ID_usuario')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor', to='compras.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioComID', to='usuarios.usuario', verbose_name='UsuarioComID'),
        ),
    ]
