# Generated by Django 4.2.3 on 2024-02-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_insumo_stock_remove_insumo_stock_min_and_more'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='prov_id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usu_id',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='usu_id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='prov_apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='prov_direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='prov_metodo_pago',
        ),
        migrations.AddField(
            model_name='compra',
            name='Proveedor_prov_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='proveedor', to='compras.proveedor', verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='Usuario_usu_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='UsuarioComID', to='usuarios.usuario', verbose_name='UsuarioCompID'),
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_estado',
            field=models.CharField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, max_length=1, verbose_name='Estado de la compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_medio_pago',
            field=models.CharField(choices=[(0, 'Efectivo'), (1, 'Transferencia'), (2, 'Tarjetas Debito o Credito'), (3, 'Transferencia Bancaria'), (4, 'Cheque')], default=0, max_length=1, verbose_name='Medio de pago de compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_nombre_proveedor',
            field=models.CharField(default=None, max_length=45, verbose_name='Nombre  del Proveedor'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='Compra_comp_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='compras.compra', verbose_name='Id Compra'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='Insumos_insumos_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.insumo', verbose_name='id insumo'),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='det_comp_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='prov_encargado',
            field=models.CharField(default=None, max_length=45, verbose_name='Encargado  del proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='prov_estado',
            field=models.CharField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, max_length=1, verbose_name='Estado del proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='prov_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='comp_fecha',
            field=models.DateField(default=None, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='comp_precio_total',
            field=models.IntegerField(default=None, verbose_name='Precio total de la compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='det_comp_cantidad',
            field=models.IntegerField(default=None, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='det_comp_precio_total',
            field=models.IntegerField(default=None, verbose_name='Procio total'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='det_comp_precio_unitario',
            field=models.IntegerField(default=None, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_nit',
            field=models.CharField(default=None, max_length=16, verbose_name='NIT del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_nombre',
            field=models.CharField(default=None, max_length=45, verbose_name='Nombre del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_num_documento',
            field=models.CharField(default=None, max_length=16, verbose_name='Numero de odentificación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_telefono',
            field=models.CharField(default=None, max_length=45, verbose_name='Telefono de proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_tipo_documento',
            field=models.CharField(default=None, max_length=15, verbose_name='Tipo de identificación del proveedor'),
        ),
    ]
